### ISSUE TITLE
Meta data (title) not updated when selecting a category filter with ajax enabled.

### ISSUE THREAD

**Issue by pimdebrabander** [EmicoEcommerce/Magento1Tweakwise#19]
Issue Brief
--
Meta data (title) not updated when selecting a category filter with ajax enabled.

Environment
--
- [ ] Tweakwise Version: 1.11.5
- [ ] Magento Version: 1.9.3.9
- [ ] Magento Enterprise: no
- [ ] Tweakwise Layered Navigation and Ajax loading enabled

Steps to reproduce
--
1. Navigate to a product list page
2. Select a different category in the filter menu

Actual result
--
1. The page title is not updated in the browser tab

Expected result
--
- [ ] The page title should be changed to the filtered category in the browser tab
